In [0]:
#####################################################
########## Welcome to TensorFlow World ##############
#####################################################
# Basic Code Structure - Graphs
#  Nodes are operators (ops), variables, and constants
#  Edges are tensors
# 0-d is a scalar
# 1-d is a vector
# 2-d is a matrix
# Etc.
# TensorFlow = Tensor + Flow = Data + Flow
from __future__ import print_function

import tensorflow as tf

In [2]:
'''
HelloWorld example using TensorFlow library.
''' 
hello=tf.constant('Hello, TensorFlow!',tf.string)
Sess=tf.Session()
Sess.run(hello)

b'Hello, TensorFlow!'

In [3]:
'''
Basic Operations example using TensorFlow library.
'''

from __future__ import print_function

import tensorflow as tf
a=tf.constant(2,tf.uint8)
b=tf.constant(3,tf.uint8)
sess=tf.Session()
print(sess.run(a*b))

6


In [0]:

# Some basic operations
x = tf.add(a, b, name="add")
y = tf.div(a, b, name="divide")

In [5]:
'''
Basic Operations example using TensorFlow library for different dataptypes using type casting.
'''
x=tf.constant(2,tf.uint32)
y=tf.constant(3,tf.float32)
sess=tf.Session()
w=tf.bitcast(tf.cast(x, tf.float32), tf.float32)
print(sess.run(w*y))
# Launch the default graph.
with tf.Session() as sess:
    print("x== %i, y =="%  a.eval(),b.eval())
    print("Addition with constants: %i" % sess.run(a+b))
    print("Multiplication with constants: %i" % sess.run(a*b))
    # print(tf.multiply(w*y))
    print ("Addition with in build function: %f"% sess.run(tf.multiply(w,y)))



6.0
x== 2, y == 3
Addition with constants: 5
Multiplication with constants: 6
Addition with in build function: 6.000000


In [6]:
#Session is the runtime environment of a graph, where operations are executed,
# and tensors are evaluated
a=tf.constant(4,tf.uint8)
b=tf.constant(4,tf.uint8)
add_var=tf.add(a,b)
with tf.Session() as session:
  print(session.run(add_var))

8


In [7]:
#Placeholders
#So far we have used Variables to manage our data, but there is a more basic structure, the placeholder.
#A placeholder is simply a variable that we will assign data to at a later date.
#It allows us to create our operations and build our computation graph, without needing the data.

x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[2. 4. 6.]


In [8]:
#######################################
######## Defining Variables ###########
#######################################

# Create three variables with some default values.
weights = tf.Variable(tf.random_normal([2, 3], stddev=0.1),
                      name="weights")
biases = tf.Variable(tf.zeros([3]), name="biases")
custom_variable = tf.Variable(tf.zeros([3]), name="custom")

# "variable_list_custom" is the list of variables that we want to initialize.
variable_list_custom = [weights, custom_variable]

# The initializer
init_custom_op = tf.variables_initializer(var_list=variable_list_custom )
print(init_custom_op)




name: "init"
op: "NoOp"
input: "^weights/Assign"
input: "^custom/Assign"



In [13]:
W2 = tf.Variable(tf.zeros((2,2)), name="weights")
W1 = tf.ones((2,2))
with tf.Session() as sess:
  print(sess.run(W1))
  sess.run(tf.initialize_all_variables())
  print(sess.run(W2))

[[1. 1.]
 [1. 1.]]
Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[0. 0.]
 [0. 0.]]
